CREATE TABLE LOAN_APPLICATION (
id INTEGER NOT NULL AUTO_INCREMENT,
FIRSTNAME varchar(255),
SURNAME varchar(255),
AMOUNT int,
TERM int
);

CREATE TABLE APPLICATION_ATTEMPT (
id INTEGER NOT NULL AUTO_INCREMENT,
REMOTE_ADDRESS VARCHAR(255),
APPLICATION_DATE DATE,
ATTEMPTS INT
);

COMMIT;