CREATE TABLE LOAN_APPLICATION (
LOAN_REFERENCE_ID int,
FIRSTNAME varchar(255),
SURNAME varchar(255),
AMOUNT int,
TERM int
);


CREATE TABLE BLOCKED_REMOTE_ADDRESS (
ID INT,
REMOTE_ADDRESS VARCHAR(255),
);